[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*

markers =
    unit: tests unitaires rapides
    functional: tests des fonctionnalités de l_API
    integration: tests utilisant des services externes comme OpenRouter

addopts = -v