"""create initial schema

Revision ID: 92d98e2d7aca
Revises: 
Create Date: 2026-07-22 00:47:56.325881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92d98e2d7aca'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('length(trim(email)) > 0', name='email_not_empty'),
    sa.CheckConstraint('length(trim(password_hash)) > 0', name='password_hash_not_empty'),
    sa.CheckConstraint('updated_at >= created_at', name='dates'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index('uq_users_email_lower', 'users', [sa.literal_column('lower(email)')], unique=True)
    op.create_table('analysis_session',
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=30), server_default='waiting_offer', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("\n            status IN (\n                'waiting_offer',\n                'ready',\n                'analyzing',\n                'completed',\n                'failed'\n            )\n            ", name='status'),
    sa.CheckConstraint('updated_at >= created_at', name='dates'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index('ix_analysis_session_user_created_at', 'analysis_session', ['user_id', 'created_at'], unique=False)
    op.create_table('document',
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('original_filename', sa.Text(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('storage_key', sa.Text(), nullable=False),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('sha256', sa.CHAR(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("mime_type = 'application/pdf'", name='mime_type'),
    sa.CheckConstraint("sha256 ~ '^[0-9a-f]{64}$'", name='sha256'),
    sa.CheckConstraint('length(trim(original_filename)) > 0', name='filename_not_empty'),
    sa.CheckConstraint('length(trim(storage_key)) > 0', name='storage_key_not_empty'),
    sa.ForeignKeyConstraint(['session_id'], ['analysis_session.session_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('document_id'),
    sa.UniqueConstraint('storage_key')
    )
    op.create_index('ix_document_session_created_at', 'document', ['session_id', 'created_at'], unique=False)
    op.create_index('ix_document_sha256', 'document', ['sha256'], unique=False)
    op.create_table('cv',
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['document.document_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('document_id')
    )
    op.create_table('job_offer',
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['document.document_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('document_id')
    )
    op.create_table('matching_analysis',
    sa.Column('analysis_id', sa.Uuid(), nullable=False),
    sa.Column('cv_document_id', sa.Uuid(), nullable=False),
    sa.Column('offer_document_id', sa.Uuid(), nullable=False),
    sa.Column('technical_skills_score', sa.SmallInteger(), nullable=False),
    sa.Column('experience_score', sa.SmallInteger(), nullable=False),
    sa.Column('projects_score', sa.SmallInteger(), nullable=False),
    sa.Column('education_score', sa.SmallInteger(), nullable=False),
    sa.Column('constraints_score', sa.SmallInteger(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('model_name', sa.String(length=150), nullable=False),
    sa.Column('prompt_version', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('constraints_score BETWEEN 0 AND 10', name='constraints_score'),
    sa.CheckConstraint('cv_document_id <> offer_document_id', name='different_documents'),
    sa.CheckConstraint('education_score BETWEEN 0 AND 10', name='education_score'),
    sa.CheckConstraint('experience_score BETWEEN 0 AND 25', name='experience_score'),
    sa.CheckConstraint('length(trim(explanation)) > 0', name='explanation_not_empty'),
    sa.CheckConstraint('length(trim(model_name)) > 0', name='model_name_not_empty'),
    sa.CheckConstraint('length(trim(prompt_version)) > 0', name='prompt_version_not_empty'),
    sa.CheckConstraint('projects_score BETWEEN 0 AND 15', name='projects_score'),
    sa.CheckConstraint('technical_skills_score BETWEEN 0 AND 40', name='technical_skills_score'),
    sa.ForeignKeyConstraint(['cv_document_id'], ['cv.document_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['offer_document_id'], ['job_offer.document_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('analysis_id')
    )
    op.create_index('ix_matching_analysis_created_at', 'matching_analysis', ['created_at'], unique=False)
    op.create_index('ix_matching_analysis_cv', 'matching_analysis', ['cv_document_id'], unique=False)
    op.create_index('ix_matching_analysis_offer', 'matching_analysis', ['offer_document_id'], unique=False)
    op.create_table('message',
    sa.Column('message_id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('context_analysis_id', sa.Uuid(), nullable=True),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('user', 'assistant', 'system')", name='role'),
    sa.CheckConstraint('length(trim(content)) > 0', name='content_not_empty'),
    sa.CheckConstraint('sequence_number > 0', name='sequence_number'),
    sa.ForeignKeyConstraint(['context_analysis_id'], ['matching_analysis.analysis_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['analysis_session.session_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('message_id'),
    sa.UniqueConstraint('session_id', 'sequence_number', name='session_sequence')
    )
    op.create_index('ix_message_context_analysis', 'message', ['context_analysis_id'], unique=False)
    op.create_table('skill_evaluation',
    sa.Column('analysis_id', sa.Uuid(), nullable=False),
    sa.Column('skill_name', sa.String(length=150), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.CheckConstraint("status IN ('matched', 'missing')", name='status'),
    sa.CheckConstraint('length(trim(skill_name)) > 0', name='skill_name_not_empty'),
    sa.ForeignKeyConstraint(['analysis_id'], ['matching_analysis.analysis_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('analysis_id', 'skill_name')
    )
    op.create_index('ix_skill_evaluation_analysis_status', 'skill_evaluation', ['analysis_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_skill_evaluation_analysis_status', table_name='skill_evaluation')
    op.drop_table('skill_evaluation')
    op.drop_index('ix_message_context_analysis', table_name='message')
    op.drop_table('message')
    op.drop_index('ix_matching_analysis_offer', table_name='matching_analysis')
    op.drop_index('ix_matching_analysis_cv', table_name='matching_analysis')
    op.drop_index('ix_matching_analysis_created_at', table_name='matching_analysis')
    op.drop_table('matching_analysis')
    op.drop_table('job_offer')
    op.drop_table('cv')
    op.drop_index('ix_document_sha256', table_name='document')
    op.drop_index('ix_document_session_created_at', table_name='document')
    op.drop_table('document')
    op.drop_index('ix_analysis_session_user_created_at', table_name='analysis_session')
    op.drop_table('analysis_session')
    op.drop_index('uq_users_email_lower', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
